### ISSUE TITLE
Unable to get the background interrupt working

### ISSUE THREAD

**Issue by BinalP** [DRISHTI-SVNIT/Rover#1]
python offers thread which are executed one after the other.
i can't figure out a way to run the threads in background for keyboard input check.
Samplecode for thread trial is attached.
[gui.txt](https://github.com/DRISHTI-SVNIT/Rover/files/873556/gui.txt)

**Comment by aniket-codedater** [comment]
I will check it out as soon as I get back my laptop or get someone else's. I hope to come back on this situation by tonight, as I am mostly getting my laptop working by then. @BinalP

**Comment by aniket-codedater** [comment]
Did you try this?
http://stackoverflow.com/questions/14043441/how-to-use-threads-to-get-input-from-keyboard-in-python-3

@BinalP
